version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: eventapp-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eventapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # app:
  #   build: .
  #   container_name: base-app
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #   environment:
  #     DB_HOST: db
  #     DB_USER: postgres
  #     DB_PASSWORD: postgres
  #     DB_NAME: events
  #     DB_PORT: 5432

volumes:
  postgres_data:
